server:
  port: 8010
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-movie

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://user:misaki@localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

# 属性配置的优先级高于代码配置。 全局配置 去掉client name 即 user-server
  user-server:
    ribbon:
      NFLoadBalancerClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    clients:
